GET http://localhost:3000/employees/1.json
Content-Type: application/json

###
GET http://localhost:3000/employees.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUzNjgxMDF9.kclJAkGOfvV93Eo4bPcSY3U_7k7hyRZ0-z_VUBsLfcU
Content-Type: application/json

###
POST http://localhost:3000/employees.json
Content-Type: application/json

{
  "department_id": 2
}

###
PATCH http://localhost:3000/employees/3.json
Content-Type: application/json

{
  "job_title": "sergeant"
}

###
DELETE http://localhost:3000/employees/2.json

### Departments - Index Request
GET http://localhost:3000/departments.json
Content-Type: application/json

### Departments - Show Request
GET http://localhost:3000/departments/2.json
Content-Type: application/json

### Departments - Create Request
POST http://localhost:3000/departments.json
Content-Type: application/json

{
  "dept_name": "Yoyo",
  "dept_code": -5,
  "dept_manager": "yoyoma"
}

### Departments - Update Request
PATCH http://localhost:3000/departments/3.json
Content-Type: application/json

{
  "dept_code": 900
}

### Departments - Delete Request
DELETE http://localhost:3000/departments/6.json

### Users - Create Request
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}